# docker-compose.yml
version: "3.8"

services:
  app:
    build: .
    container_name: crm_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db/crm
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: crm_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
